import {
  File,
  FileCode,
  FileCss,
  FileHtml,
  FileImage,
  FileIni,
  FileJpg,
  FileJs,
  FileJsx,
  FileLock,
  FileMd,
  FilePng,
  FilePy,
  FileRs,
  FileSql,
  FileSvg,
  FileText,
  FileTs,
  FileTsx,
  FileVue,
  type Icon,
} from "@phosphor-icons/react";

const BY_EXT: Record<string, Icon> = {
  ts: FileTs,
  mts: FileTs,
  cts: FileTs,
  tsx: FileTsx,
  js: FileJs,
  mjs: FileJs,
  cjs: FileJs,
  jsx: FileJsx,
  rs: FileRs,
  py: FilePy,
  go: FileCode,
  java: FileCode,
  kt: FileCode,
  rb: FileCode,
  php: FileCode,
  c: FileCode,
  h: FileCode,
  cpp: FileCode,
  cc: FileCode,
  hpp: FileCode,
  cs: FileCode,
  swift: FileCode,
  sh: FileCode,
  bash: FileCode,
  zsh: FileCode,
  fish: FileCode,
  md: FileMd,
  mdx: FileMd,
  markdown: FileMd,
  json: FileCode,
  jsonc: FileCode,
  yaml: FileCode,
  yml: FileCode,
  toml: FileCode,
  ini: FileIni,
  env: FileIni,
  conf: FileIni,
  cfg: FileIni,
  sql: FileSql,
  css: FileCss,
  scss: FileCss,
  less: FileCss,
  html: FileHtml,
  htm: FileHtml,
  vue: FileVue,
  svg: FileSvg,
  png: FilePng,
  jpg: FileJpg,
  jpeg: FileJpg,
  gif: FileImage,
  webp: FileImage,
  bmp: FileImage,
  ico: FileImage,
  lock: FileLock,
  txt: FileText,
  log: FileText,
};

const BY_NAME: Record<string, Icon> = {
  "docker-compose.yml": FileCode,
  "docker-compose.yaml": FileCode,
  "compose.yml": FileCode,
  "compose.yaml": FileCode,
  makefile: FileCode,
  "package-lock.json": FileLock,
  "pnpm-lock.yaml": FileLock,
  "yarn.lock": FileLock,
  "cargo.lock": FileLock,
  "bun.lock": FileLock,
  "bun.lockb": FileLock,
};

export function fileIcon(name: string): Icon {
  const lower = name.toLowerCase();
  const byName = BY_NAME[lower];
  if (byName) return byName;
  if (lower === "dockerfile" || lower.startsWith("dockerfile.")) return FileCode;
  if (lower.startsWith(".")) return FileIni;
  const dot = lower.lastIndexOf(".");
  const ext = dot > 0 ? lower.slice(dot + 1) : "";
  return BY_EXT[ext] ?? File;
}
